#!/bin/bash
set -u

GMOD_DIR="/home/gmod/server/garrysmod"
CFG_DIR="${GMOD_DIR}/cfg"
MAPCYCLE_FILE="${CFG_DIR}/mapcycle.txt"
ADDONS_DIR="${GMOD_DIR}/addons"
STEAMCMD="/home/gmod/steamcmd/steamcmd.sh"
WORKSHOP_DIR="/home/gmod/server/steamapps/workshop/content/4000"

mkdir -p "${CFG_DIR}" "${ADDONS_DIR}"

# ---------------------------------------------------------------------------
# Sync addons + gamemodes from read-only /srv mounts into the actual game
# tree. Mounting host directories directly on top of garrysmod/{addons,
# gamemodes} caused srcds (on Docker Desktop / WSL2 9p) to silently fail
# enumerating the directories, so terrortown and the workshop content were
# never discovered. We therefore mount the sources to /srv/* and rsync
# them into image-internal paths on every start.
# ---------------------------------------------------------------------------
sync_dir() {
    local src="$1" dst="$2"
    [ -d "${src}" ] || return 0
    mkdir -p "${dst}"
    if command -v rsync >/dev/null 2>&1; then
        rsync -a --delete \
            --exclude 'ws_*' \
            "${src}/" "${dst}/"
    else
        # cp -a fallback: best effort, no deletion of stale files
        cp -a "${src}/." "${dst}/"
    fi
}

# Only sync gamemodes if the host actually provides override files.
# An empty /srv/gamemodes (just the mount target, no real content) would
# otherwise cause rsync --delete to wipe the container's stock gamemodes
# (terrortown, sandbox, base) installed by SteamCMD.
sync_gamemodes_if_present() {
    local src="/srv/gamemodes"
    [ -d "${src}" ] || return 0
    # Anything other than dotfiles / .gitkeep counts as user override.
    if [ -z "$(find "${src}" -mindepth 1 -maxdepth 1 ! -name '.*' -print -quit 2>/dev/null)" ]; then
        echo "No host-side gamemode overrides found, keeping container defaults."
        return 0
    fi
    sync_dir "${src}" "${GMOD_DIR}/gamemodes"
}

sync_dir /srv/addons "${ADDONS_DIR}"
sync_gamemodes_if_present


# ---------------------------------------------------------------------------
# Workshop addon download
#
# WORKSHOP_IDS env may contain one or many Steam Workshop addon IDs separated
# by comma, semicolon, space or newline, e.g.:
#   WORKSHOP_IDS="121287462 807428039 356664308"
#
# Each addon is fetched anonymously via steamcmd workshop_download_item for
# Garry's Mod (app 4000). The resulting .gma files are linked into
# garrysmod/addons/ so the dedicated server loads them at startup. The
# matching client-side download is handled by the ttt-workshop addon's
# resource.AddWorkshop calls.
# ---------------------------------------------------------------------------
WORKSHOP_LIST=()
if [ -n "${WORKSHOP_IDS:-}" ]; then
    WS_NORMALIZED=$(echo "${WORKSHOP_IDS}" | tr ',;\n\r\t' '    ')
    # shellcheck disable=SC2206
    WS_RAW=( ${WS_NORMALIZED} )
    for id in "${WS_RAW[@]}"; do
        [ -n "${id}" ] && WORKSHOP_LIST+=("${id}")
    done
fi

# ---------------------------------------------------------------------------
# Generate the client-side resource.AddWorkshop addon from WORKSHOP_LIST so
# the IDs do not have to be maintained in two places. The file is written
# AFTER the rsync above, so it lives only inside the container.
# ---------------------------------------------------------------------------
TTT_WS_ADDON_DIR="${ADDONS_DIR}/ttt-workshop"
TTT_WS_LUA_DIR="${TTT_WS_ADDON_DIR}/lua/autorun/server"
TTT_WS_LUA_FILE="${TTT_WS_LUA_DIR}/sv_ttt_workshop.lua"
mkdir -p "${TTT_WS_LUA_DIR}"
if [ ! -f "${TTT_WS_ADDON_DIR}/addon.json" ]; then
    cat > "${TTT_WS_ADDON_DIR}/addon.json" <<'EOF'
{
    "title":       "TTT Phoenix Workshop",
    "type":        "ServerContent",
    "tags":        [ "fun", "roleplay" ],
    "ignore":      []
}
EOF
fi
{
    echo "-- AUTO-GENERATED by assets/start.sh from WORKSHOP_IDS."
    echo "-- Do not edit by hand; change WORKSHOP_IDS in docker-compose.yaml instead."
    echo ""
    echo "local ids = {"
    for id in "${WORKSHOP_LIST[@]}"; do
        printf '    "%s",\n' "${id}"
    done
    echo "}"
    echo ""
    echo "for _, id in ipairs(ids) do"
    echo "    resource.AddWorkshop(id)"
    echo "end"
} > "${TTT_WS_LUA_FILE}"
echo "Wrote ${TTT_WS_LUA_FILE} with ${#WORKSHOP_LIST[@]} workshop ID(s)."

if [ "${#WORKSHOP_LIST[@]}" -gt 0 ] && [ -x "${STEAMCMD}" ]; then
    echo "Downloading ${#WORKSHOP_LIST[@]} workshop addon(s)..."
    STEAM_ARGS=( +force_install_dir /home/gmod/server +login anonymous )
    for id in "${WORKSHOP_LIST[@]}"; do
        STEAM_ARGS+=( +workshop_download_item 4000 "${id}" )
    done
    STEAM_ARGS+=( +quit )
    "${STEAMCMD}" "${STEAM_ARGS[@]}" || \
        "${STEAMCMD}" "${STEAM_ARGS[@]}" || \
        echo "WARN: steamcmd workshop download failed; continuing without it"

    for id in "${WORKSHOP_LIST[@]}"; do
        # steamcmd may store the GMA either as <id>.gma or as a hashed
        # *_legacy.bin file. Pick the largest matching file.
        SRC=$(find "${WORKSHOP_DIR}/${id}" -maxdepth 1 -type f \
                \( -name '*.gma' -o -name '*.bin' \) -printf '%s\t%p\n' 2>/dev/null \
              | sort -rn | head -n1 | cut -f2-)
        if [ -z "${SRC}" ] || [ ! -f "${SRC}" ]; then
            echo "  WARN: workshop ${id} GMA not found in ${WORKSHOP_DIR}/${id}"
            continue
        fi

        # GMod's gameinfo.txt mounts addons via 'game+mod garrysmod/addons/*'
        # which only picks up extracted addon directories, not raw .gma files.
        # We therefore decompress (if needed) and extract every workshop GMA
        # into garrysmod/addons/ws_<id>/ using gmad_linux.
        TMP_GMA="/tmp/ws_${id}.gma"
        EXTRACT_DIR="${ADDONS_DIR}/ws_${id}"
        rm -rf "${EXTRACT_DIR}" "${ADDONS_DIR}/ws_${id}.gma" "${TMP_GMA}"

        # Detect format. Valid GMA starts with ASCII 'GMAD'. Workshop
        # *_legacy.bin files are LZMA1-compressed (props byte 0x5D) without
        # an end-of-stream marker (so unlzma exits non-zero even on success).
        MAGIC=$(head -c 4 "${SRC}" 2>/dev/null || true)
        FIRST_BYTE=$(head -c 1 "${SRC}" | od -An -tx1 | tr -d ' \n')
        if [ "${MAGIC}" = "GMAD" ]; then
            cp -f "${SRC}" "${TMP_GMA}"
        elif [ "${FIRST_BYTE}" = "5d" ]; then
            unlzma -c "${SRC}" > "${TMP_GMA}" 2>/dev/null || true
        else
            cp -f "${SRC}" "${TMP_GMA}"
        fi

        NEW_MAGIC=$(head -c 4 "${TMP_GMA}" 2>/dev/null || true)
        if [ "${NEW_MAGIC}" != "GMAD" ]; then
            echo "  WARN: workshop ${id} produced no valid GMA from ${SRC}"
            rm -f "${TMP_GMA}"
            continue
        fi

        mkdir -p "${EXTRACT_DIR}"
        if /home/gmod/server/bin/gmad_linux extract \
                -file "${TMP_GMA}" -out "${EXTRACT_DIR}" >/dev/null 2>&1; then
            echo "  extracted workshop ${id} -> ${EXTRACT_DIR} (src=${SRC})"
        else
            echo "  WARN: workshop ${id} gmad_linux extract failed"
            rm -rf "${EXTRACT_DIR}"
        fi
        rm -f "${TMP_GMA}"
    done
fi

# ---------------------------------------------------------------------------
# Map rotation / randomization
#
# MAPS env may contain one or many maps separated by comma, semicolon, space
# or newline, e.g.:
#   MAPS="ttt_minecraft_b5, ttt_67thway_v3, ttt_clue_se"
#
# All maps are written (shuffled) into garrysmod/cfg/mapcycle.txt, which
# srcds rotates through automatically when a map ends. The initial map is
# also picked randomly from the list. If MAPS is empty, $MAP is used.
# ---------------------------------------------------------------------------
MAP_LIST=()
if [ -n "${MAPS:-}" ]; then
    NORMALIZED=$(echo "${MAPS}" | tr ',;\n\r\t' '    ')
    # shellcheck disable=SC2206
    RAW=( ${NORMALIZED} )
    for m in "${RAW[@]}"; do
        [ -n "${m}" ] && MAP_LIST+=("${m}")
    done
fi

if [ "${#MAP_LIST[@]}" -eq 0 ]; then
    MAP_LIST=("${MAP}")
fi

shuffle() {
    local i tmp size max rand
    size=${#MAP_LIST[@]}
    for ((i=size-1; i>0; i--)); do
        max=$(( i + 1 ))
        rand=$(( RANDOM % max ))
        tmp=${MAP_LIST[i]}
        MAP_LIST[i]=${MAP_LIST[rand]}
        MAP_LIST[rand]=${tmp}
    done
}
shuffle

: > "${MAPCYCLE_FILE}"
for m in "${MAP_LIST[@]}"; do
    echo "${m}" >> "${MAPCYCLE_FILE}"
done

START_MAP="${MAP_LIST[0]}"

echo "Map rotation (${#MAP_LIST[@]} maps), starting on: ${START_MAP}"
echo "Full cycle:"
sed 's/^/  - /' "${MAPCYCLE_FILE}"

EXTRA_ARGS="${ARGS:-}"

# ---------------------------------------------------------------------------
# RCON bootstrap
# srcds only enables the RCON TCP listener when rcon_password is non-empty
# at startup. We therefore inject a password into server.cfg BEFORE srcds
# boots (auto-generated if RCON_PASSWORD env is unset). Also written to
# /home/gmod/rcon_password.txt so manage.ps1 (or the user) can read it.
# ---------------------------------------------------------------------------
SERVER_CFG="${CFG_DIR}/server.cfg"
touch "${SERVER_CFG}"
EXISTING_PW=$(grep -E '^[[:space:]]*rcon_password' "${SERVER_CFG}" 2>/dev/null | head -1 | sed -E 's/.*"([^"]+)".*/\1/')
if [ -n "${RCON_PASSWORD:-}" ]; then
    RCON_PW="${RCON_PASSWORD}"
elif [ -n "${EXISTING_PW}" ]; then
    RCON_PW="${EXISTING_PW}"
else
    RCON_PW=$(head -c 16 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 20)
fi
# Replace any existing rcon_password line, otherwise append.
if grep -qE '^[[:space:]]*rcon_password' "${SERVER_CFG}"; then
    sed -i -E "s|^[[:space:]]*rcon_password.*|rcon_password \"${RCON_PW}\"|" "${SERVER_CFG}"
else
    printf '\nrcon_password "%s"\n' "${RCON_PW}" >> "${SERVER_CFG}"
fi
echo "${RCON_PW}" > /home/gmod/rcon_password.txt
chmod 600 /home/gmod/rcon_password.txt
echo "RCON enabled (password written to /home/gmod/rcon_password.txt)"
EXTRA_ARGS="+rcon_password \"${RCON_PW}\" ${EXTRA_ARGS}"

# ---------------------------------------------------------------------------
# TTT default cvars
# Inject reasonable defaults into server.cfg if no ttt_minimum_players is
# present yet (i.e. fresh container). manage.ps1 option 5 manages its own
# block via marker comments and will not collide.
# ---------------------------------------------------------------------------
if ! grep -qE '^[[:space:]]*ttt_minimum_players' "${SERVER_CFG}"; then
    cat >> "${SERVER_CFG}" <<'EOF'

// ---- TTT defaults injected by start.sh ----
ttt_minimum_players 2
ttt_round_limit 6
ttt_time_limit_minutes 75
ttt_haste 1
ttt_haste_starting_minutes 5
ttt_haste_minutes_per_death 0.5
ttt_postround_dm 0
ttt_namechange_kick 0
ttt_no_nade_throw_during_prep 1
sv_voiceenable 1
sv_alltalk 0
mp_friendlyfire 0
EOF
    echo "Wrote TTT default cvars to ${SERVER_CFG}"
fi

if [ -n "${HOSTNAME:-}" ]; then
    EXTRA_ARGS="+hostname \"${HOSTNAME}\" ${EXTRA_ARGS}"
elif [ -n "${NAME:-}" ]; then
    EXTRA_ARGS="+hostname \"${NAME}\" ${EXTRA_ARGS}"
fi

if [ -n "${GSLT:-}" ]; then
    EXTRA_ARGS="+sv_setsteamaccount \"${GSLT}\" ${EXTRA_ARGS}"
fi

if [ -n "${AUTHKEY:-}" ]; then
    EXTRA_ARGS="-authkey \"${AUTHKEY}\" ${EXTRA_ARGS}"
fi

EXTRA_ARGS="+mapcyclefile \"cfg/mapcycle.txt\" ${EXTRA_ARGS}"

if [ -n "${PRODUCTION:-}" ] && [ "${PRODUCTION}" -ne 0 ]; then
    MODE="production"
    EXTRA_ARGS="-disableluarefresh ${EXTRA_ARGS}"
else
    MODE="development"
    EXTRA_ARGS="-debug ${EXTRA_ARGS}"
fi

echo "Starting server on ${MODE} mode..."

eval exec /home/gmod/server/srcds_run \
    -game garrysmod \
    -norestart \
    -strictportbind \
    -autoupdate \
    -steam_dir "/home/gmod/steamcmd" \
    -steamcmd_script "/home/gmod/update.txt" \
    -port "${PORT}" \
    -maxplayers "${MAXPLAYERS}" \
    +gamemode "${GAMEMODE}" \
    +map "${START_MAP}" \
    "${EXTRA_ARGS}"